admin/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('login.urls')),
]

dgm/urls.py
from django.contrib import admin
from django.conf.urls import include,url
from django.urls import path
from . import views



app_name='dgm'
urlpatterns = [
    # path('communication/',views.communication,name='communication'),
    # path('',views.main.choice,name='choice'),
    path('navigation/', views.navigation,name='navigation'),
    # path('surveillance/', views.navigation,name='sur')
    path('<str:id>/<str:name>', views.details,name='details'),
    path('communication/',views.communication),
	



]

supervisor/urls.py
from django.contrib import admin
from django.conf.urls import include,url
from django.urls import path
from . import views
from engineer import views as eviews
app_name='supervisor'
urlpatterns = [
    path('employee/<str:id>',views.main.empdetails,name='empdetails'),
    # path('',views.main.choice,name='choice'),
    path('<str:id>/<str:name>', views.main.details,name='details'),
    path('sendmail/<str:id>/',views.main.mail,name='sendmail'),
    path('sent/',views.main.sent,name='sent'),
    path('abc/',views.cdvor.daily,name='cdvordaily'),
    path('xyz/',views.datis.daily,name='datisdaily'),
    path('dmedaily/',views.dme.daily,name='dmedaily'),
    path('dscndaily/',views.dscn.daily,name='dscndaily'),
    path('ndb/',views.ndb.daily,name='ndbdaily'),
    path('scctvdaily/',views.scctv.daily,name='scctvdaily'),
    path('cdvorweekly/',views.cdvor.weekly,name='cdvorweekly'),
    path('datisweekly/',views.datis.weekly,name='datisweekly'),
    path('dmeweekly/',views.dme.weekly,name='dmeweekly'),
    path('dscnweekly/',views.dscn.weekly,name='dscnweekly'),
    path('scctvweekly/',views.scctv.weekly,name='scctvweekly'),
    #path('ndb/',views.ndb.weekly,name='ndbweekly'),
    #path('vhfweekly/',views.vhf.weekly,name='vhfweekly'),
    #path('vhfdaily/',views.vhf.daily,name='vhfdaily'),
    path('scctvdaily/',views.scctv.daily,name='scctvdaily'),
    path('cdvormonthly/',views.cdvor.monthly,name='cdvormonthly'),
    # path('datismonthly/',views.datis.monthly,name='datismonthly'),
    path('dmemonthly/',views.dme.monthly,name='dmemonthly'),
    path('dscnmonthly/',views.dscn.monthly,name='dscnmonthly'),
    path('ndb/',views.ndb.monthly,name='ndbmonthly'),
    path('vhfmonthly/',views.vhf.monthly,name='vhfmonthly'),
    path('scctvmonthly/',views.scctv.monthly,name='scctvmonthly'),
    path('verify/<str:names>/<str:id>',views.main.verify,name='verify'),
    
   
    # path('employee/',views.employee)
    # path('officer/',views.officer)
    # path('install/', views.install),
    #  path('dummy/', views.dummy),
    #  path('test/', views.test)
]

supervisor/views.py
from django.shortcuts import render
from login import models as mod
# Create your views here.
def test(request):
    print("here")

    x=mod.Supervisor.objects.all()
    for i in x:
        print(i.emp_id)
    return render(request,'supervisor/supervisor.html')

supervisor/views/cdvor.py
from django.shortcuts import render
from login import models as models
from django.http import HttpResponse,HttpResponseRedirect
from . import main
def daily(request):
    cdvordaily=[entry for entry in models.Cdvordaily.objects.all().values().order_by('-date')]
    for i in cdvordaily:
        i['token']=main.encode(request,str(i['p_id']))
        if i['unit_incharge_approval']=="YES":
           i['flag']=1
        elif['unit_incharge_approval']=="NO":
           i['flag']=0
        else:
           i['flag']=9

    return render(request,'supervisor/list_details.html',{'context':cdvordaily,'name':'Cdvordaily'}) 

def weekly(request):
    cdvorweekly=[entry for entry in models.Cdvorweekly.objects.all().values().order_by('-date')]
    for i in cdvorweekly:
        i['token']=main.encode(request,str(i['p_id']))
        if i['unit_incharge_approval']=="YES":
           i['flag']=1
        elif['unit_incharge_approval']=="NO":
           i['flag']=0
        else:
           i['flag']=9

    return render(request,'supervisor/list_details.html',{'context':cdvorweekly,'name':'Cdvorweekly'})         

def monthly(request):
    cdvormonthly=[entry for entry in models.Cdvormonthly.objects.all().values().order_by('-date')]
    for i in cdvormonthly:
        i['token']=main.encode(request,str(i['p_id']))
        if i['unit_incharge_approval']=="YES":
           i['flag']=1
        elif['unit_incharge_approval']=="NO":
           i['flag']=0
        else:
           i['flag']=9
    
    return render(request,'supervisor/list_details.html',{'context':cdvormonthly,'name':'Cdvormonthly'})

supervisor/views/datis.py
from django.shortcuts import render
from login import models as models
from django.http import HttpResponse,HttpResponseRedirect
from . import main

def daily(request):
    datisdaily=[entry for entry in models.Datisdaily.objects.all().values().order_by('-date')]
   #  sorted(datisdaily,key=itemgetter('date'),reverse=True)
    for i in datisdaily:
        i['token']=main.encode(request,str(i['p_id']))
        if i['unit_incharge_approval']=="YES":
           i['flag']=1
        elif['unit_incharge_approval']=="NO":
           i['flag']=0
        else:
           i['flag']=9
    return render(request,'supervisor/list_details.html',{'context':datisdaily,'name':'Datisdaily'})


# def monthly(request):
#     Datismonthly=[entry for entry in models.Datismonthly.objects.all().values()order_by('-date')]
#     return render(request,'supervisor/monthly_details.html',{'context':Datismonthly,'name':'Datismonthly'}) 
def weekly(request):
    Datisweekly=[entry for entry in models.Datisweekly.objects.all().values().order_by('-date')]
    for i in Datisweekly:
        i['token']=main.encode(request,str(i['p_id']))
        if i['unit_incharge_approval']=="YES":
           i['flag']=1
        elif['unit_incharge_approval']=="NO":
           i['flag']=0
        else:
           i['flag']=9
    
    return render(request,'supervisor/list_details.html',{'context':Datisweekly,'name':'Datisweekly'})

supervisor/views/dme.py
from django.shortcuts import render
from login import models as models
from django.http import HttpResponse,HttpResponseRedirect
from . import main
def daily(request):
    dmedaily=[entry for entry in models.Dmedaily.objects.all().values().order_by('-date')]
    for i in dmedaily:
        i['token']=main.encode(request,str(i['p_id']))
        if i['unit_incharge_approval']=="YES":
           i['flag']=1
        elif['unit_incharge_approval']=="NO":
           i['flag']=0
        else:
           i['flag']=9
    return render(request,'supervisor/list_details.html',{'context':dmedaily,'name':'Dmedaily'})

def monthly(request):
    dmemonthly=[entry for entry in models.Dmemonthly.objects.all().values().order_by('-date')]
    for i in dmemonthly:
        i['token']=main.encode(request,str(i['p_id']))
        if i['unit_incharge_approval']=="YES":
           i['flag']=1
        elif['unit_incharge_approval']=="NO":
           i['flag']=0
        else:
           i['flag']=9
    
    return render(request,'supervisor/list_details.html',{'context':dmemonthly,'name':'Dmemonthly'})
    
    
def weekly(request):
    dmeweekly=[entry for entry in models.Dmeweekly.objects.all().values().order_by('-date')]
    for i in dmeweekly:
        i['token']=main.encode(request,str(i['p_id']))
        if i['unit_incharge_approval']=="YES":
           i['flag']=1
        elif['unit_incharge_approval']=="NO":
           i['flag']=0
        else:
           i['flag']=9
    return render(request,'supervisor/list_details.html',{'context':dmeweekly,'name':'Dmeweekly'})
    return 0

supervisor/views/dscn.py
from django.shortcuts import render
from login import models as models
from django.http import HttpResponse,HttpResponseRedirect
# from . import main
from . import main
def daily(request):
    dscndaily=[entry for entry in models.Dscndaily.objects.all().values().order_by('-date')]
    for i in dscndaily:
       i['token']=main.encode(request,str(i['p_id']))
       if i['unit_incharge_approval']=="YES":
           i['flag']=1
       elif['unit_incharge_approval']=="NO":
           i['flag']=0
       else:
           i['flag']=9
    
    return render(request,'supervisor/list_details.html',{'context':dscndaily,'name':'Dscndaily'})

def monthly(request):
    dscnmonthly=[entry for entry in models.Dscnmonthly.objects.all().values().order_by('-date')]
    for i in dscnmonthly:
        i['token']=main.encode(request,str(i['p_id']))
        if i['unit_incharge_approval']=="YES":
           i['flag']=1
        elif['unit_incharge_approval']=="NO":
           i['flag']=0
        else:
           i['flag']=9
    
    return render(request,'supervisor/list_details.html',{'context':dscnmonthly,'name':'Dscnmonthly'})

def weekly(request):
    dscnweekly=[entry for entry in models.Dscnweekly.objects.all().values().order_by('-date')]
    for i in dscnweekly:
        i['token']=main.encode(request,str(i['p_id']))
        if i['unit_incharge_approval']=="YES":
           i['flag']=1
        elif['unit_incharge_approval']=="NO":
           i['flag']=0
        else:
           i['flag']=9
    
    return render(request,'supervisor/list_details.html',{'context':dscnweekly,'name':'Dscnweekly'})

supervisor/views/ndb.py
from django.shortcuts import render
from login import models as models
from django.http import HttpResponse,HttpResponseRedirect
from . import main
def daily(request):
    ndbdaily=[entry for entry in models.Ndbdaily.objects.all().values().order_by('-date')]
    for i in ndbdaily:
        i['token']=main.encode(request,str(i['p_id']))
        if i['unit_incharge_approval']=="YES":
           i['flag']=1
        elif['unit_incharge_approval']=="NO":
           i['flag']=0
        else:
           i['flag']=9
    return render(request,'supervisor/list_details.html',{'context':ndbdaily,'name':'Ndbdaily'})
def monthly(request):
   ndbmonthly=[entry for entry in models.Ndbmonthly.objects.all().values().order_by('-date')]
   for i in ndbmonthly:
        i['token']=main.encode(request,str(i['p_id']))
        if i['unit_incharge_approval']=="YES":
           i['flag']=1
        elif['unit_incharge_approval']=="NO":
           i['flag']=0
        else:
           i['flag']=9
    
   return render(request,'supervisor/list_details.html',{'context':Ndbmonthly,'name':'Ndbmonthly'})

def weekly(request):
    ndbweekly=[entry for entry in models.Ndbweekly.objects.all().values().order_by('-date')]
    for i in ndbweekly:
        i['token']=main.encode(request,str(i['p_id']))
        if i['unit_incharge_approval']=="YES":
           i['flag']=1
        elif['unit_incharge_approval']=="NO":
           i['flag']=0
        else:
           i['flag']=9
    
    return render(request,'supervisor/list_details.html',{'context':ndbweekly,'name':'Ndbweekly'})

supervisor/views/scctv.py
from django.shortcuts import render
from login import models as models
from django.http import HttpResponse,HttpResponseRedirect
from . import main
def daily(request):
    scctvdaily=[entry for entry in models.Scctvdaily.objects.all().values().order_by('-date')]
    for i in scctvdaily:
        i['token']=main.encode(request,str(i['p_id']))
        if i['unit_incharge_approval']=="YES":
           i['flag']=1
        elif['unit_incharge_approval']=="NO":
           i['flag']=0
        else:
           i['flag']=9
    return render(request,'supervisor/list_details.html',{'context':scctvdaily,'name':'Scctvdaily'})


def monthly(request):
    scctvmonthly=[entry for entry in models.Scctvmonthly.objects.all().values().order_by('-date')]
    for i in scctvmonthly:
        i['token']=main.encode(request,str(i['p_id']))
        if i['unit_incharge_approval']=="YES":
           i['flag']=1
        elif['unit_incharge_approval']=="NO":
           i['flag']=0
        else:
           i['flag']=9
    
    return render(request,'supervisor/list_details.html',{'context':scctvmonthly,'name':'Scctvmonthly'})

def weekly(request):
    scctvweekly=[entry for entry in models.Scctvweekly.objects.all().values().order_by('-date')]
    for i in scctvweekly:
        i['token']=main.encode(request,str(i['p_id']))
        if i['unit_incharge_approval']=="YES":
           i['flag']=1
        elif['unit_incharge_approval']=="NO":
           i['flag']=0
        else:
           i['flag']=9
    
    return render(request,'supervisor/list_details.html',{'context':scctvweekly,'name':'Scctvweekly'})

supervisor/views/vhf.py
from django.shortcuts import render
from login import models as models
from django.http import HttpResponse,HttpResponseRedirect
from . import main
def daily(request):
    vhfdaily=[entry for entry in models.Vhfdaily.objects.all().values().order_by('-date')]
    for i in vhfdaily:
        i['token']=main.encode(request,str(i['p_id']))
        if i['unit_incharge_approval']=="YES":
           i['flag']=1
        elif['unit_incharge_approval']=="NO":
           i['flag']=0
        else:
           i['flag']=9
    return render(request,'supervisor/list_details.html',{'context':vhfdaily,'name':'Vhfdaily'})


# def monthly(request):
#     vhfmonthly=[entry for entry in models.vhfmonthly.objects.all().values().order_by('-date')]
#     return render(request,'supervisor/monthly_details.html',{'context':vhfmonthly,'name':'vhfmonthly'}) 
def weekly(request):
    vhfweekly=[entry for entry in models.Vhfweekly.objects.all().values().order_by('-date')]
    for i in vhfweekly:
        i['token']=main.encode(request,str(i['p_id']))
        if i['unit_incharge_approval']=="YES":
           i['flag']=1
        elif['unit_incharge_approval']=="NO":
           i['flag']=0
        else:
           i['flag']=9
    
    return render(request,'supervisor/list_details.html',{'context':vhfweekly,'name':'Vhfweekly'})
def monthly(request):
    vhfmonthly=[entry for entry in models.Vhfmonthly.objects.all().values().order_by('-date')]
    for i in vhfmonthly:
        i['token']=main.encode(request,str(i['p_id']))
        if i['unit_incharge_approval']=="YES":
           i['flag']=1
        elif['unit_incharge_approval']=="NO":
           i['flag']=0
        else:
           i['flag']=9
    
    return render(request,'supervisor/list_details.html',{'context':vhfmonthly,'name':'Vhfmonthly'})

supervisor/templates/supervisor/employee_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Daily DATIS Maintenance Report</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'supervisor/datisstyle.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Gotu&family=Righteous&display=swap" rel="stylesheet">
</head>
<body>
    <div class="container">
        <nav class="navbar sticky-top">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href='/' onclick="window.location.href='/'" class="taskbut"><img src="{% static '/images/task.png' %}"></a>
                </li>
            </ul>
            <div class="title-header">PREVENTIVE MAINTENANCE LOG<img src="{% static '/images/aai.jpg' %}"></div>
        </nav>
        <br>
        
        <div class="card" style="width:40%; height: 8rem; margin-left:30%; text-align: center;">
                <div class="card-body" style="font-family: 'Times New Roman', Times, serif; font-weight: bold; color:white;font-size: 20px; background-color: #1E27FA">
                            <h4 class="title" style="font-weight: bold;">Name:{{e_name}}<br> Designation: {{e_desig}}</h4>
                            <button class="btn  contactbut" data-toggle="modal" data-target="#contactengg" href='#'>Contact</a>
            </div>
        </div>
                <div class="modal fade" id="contactengg">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                              <h4 class="modal-title">ENGINEER</h4><!-- Need to enter details -->
                              <button type="button" class="close" data-dismiss="modal">&times;</button>
                            </div>
                            <div class="modal-body">
                              <h5>{{e_name}}</h5>
                              <h6>Email: <a href="mailto:surajshah@aai.com">{{e_email}}</a></h6>
                              <h6>Phone:{{e_contact}}</h6>
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                            </div>  
                        </div>
                    </div>
                </div>

        <br>        
        <table class="table table-bordered table-condensed table-striped table-hover todaytasks">
            <thead>
                <tr>  
                    <th>Report ID</th>
                    <th>Report Type</th>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Submission Status</th>
                    <th>Approval Status</th>

                </tr>
            </thead>
            <tbody>
                {% for i in datis %}
                <tr data-href="/schoice/{{i.token}}/{{i.type}}">
                    <td>{{i.p_id}}</td>
                    <td>{{i.type}}</td>
                    <td>{{i.date}}</td>
                    <td>{{i.time}}</td>
                    <td>{{i.status}}</td>
                    <td>{{i.unit_incharge_approval}}</td>
                </tr>
                {% endfor %}
             </tbody>
        </table>
    </div>
<script type="text/javascript">
    $(function(){
    $('.table tr[data-href]').each(function(){
        $(this).css('cursor','pointer').hover(
            function(){ 
                $(this).addClass('active'); 
            },  
            function(){ 
                $(this).removeClass('active'); 
            }).click( function(){ 
                document.location = $(this).attr('data-href'); 
            }
        );
    });
});
</script>             
</body>
</html>

supervisor/templates/supervisor/list_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Reports</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	 <link rel="stylesheet" type="text/css" href="{% static 'supervisor/home.css' %}">
	  <link rel="stylesheet" type="text/css" href="home.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> 
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

	<link href="https://fonts.googleapis.com/css2?family=Gotu&family=Righteous&display=swap" rel="stylesheet">
		<style>
		.active a 
		{
		  background-color: #1E72FA !important; 
		  color: white !important; 
		}
		.todays
{
	color:#1E72FA; 
}
.faculty
{
	color:#1E72FA;
}
.fac 
{
	max-height: 34rem!important;
}
.tod
{
	max-height: 34rem!important;
}
.container {
  text-align: center;
  display: absolute;
  position: relative;
  height: auto;
  margin: auto;
  box-shadow: 1px 5px 10px 1px #333;
 /* overflow: hidden;*/
}
.taskbut img{
	height:40px;
	margin-top:20px;
}
.title-header
{
	padding-left:30px;font-size: 30px; background-color: #1E27FA ; color: white; font-family: 'Righteous', cursive; text-align: right;
}
.title-header img
{
	height:80px; margin-top: 7px; margin-left:0rem; 
}

	</style>
</head>
<body>
    <div class="container" >	
	    		
		
		<nav class="navbar sticky-top">
			<ul class="navbar-nav">
	    		<li class="nav-item" style="list-style-type:none;">
	      			<a href='/' onclick="window.location.href='/'" class="taskbut"><img src="{% static '/images/task.png' %}"></a>		
	    		</li>
	    	</ul>
			<div class="title-header">PREVENTIVE MAINTENANCE LOG <img src="{% static '/images/aai.jpg' %}"></div>
			
		</nav>
		<div class="row">
			<div class="card" style="width:40%; height: 7rem; margin-left:30%; text-align: center;">
				<div class="card-body" style="font-family: 'Times New Roman', Times, serif; font-weight: bold; color:white;font-size: 20px; background-color: #1E27FA">
					        <h2 class="title" style="padding:10px; font-weight: bold;">{{ name }}</h2>
					<!-- Enter the maintainence type details here -->
			 	</div>
			</div>

			<div class="data-tab" style="margin-top: 2rem;">
				<div class="col-md-2"> 
				</div>
				<div class="col-md-3" >
					<div class="row"> 
					</div>
					<div class="card tabcard" style="height:35rem !important; background-color: #ffffff!important">
						<ul class="nav nav-pills nav-stacked">
						    <li style="background-color:#DBDBDB; font-size:16px"><a class="todays" data-toggle="pill" href="#pending" >Unverified</a></li>
						    <li style="background-color:#DBDBDB;font-size:16px"><a class="todays" data-toggle="pill" href="#approved" >Approved</a></li>
						    <li style="background-color:#DBDBDB;font-size:16px"><a class="todays" data-toggle="pill" href="#declined" >Declined</a></li>
						    
						 </ul>
					</div>
				</div>
			</div>
			<div class="col-md-4 card tabcol" style="height:35rem!important;">
				<div class="tab-content">
					<div id="default" class="tab-pane fade in active tod ">		  
				       <h5 style="margin:7rem; font-weight: bold; font-family: 'Times New Roman', Times, serif; ">On left, choose the section of report to be viewed.</h5>
				    </div>

		    		<div id="pending" class="tab-pane fade fac">		  
				        <table class="table table-bordered table-condensed table-striped table-hover todaytasks">
				            <thead>
				                <tr>
				                	<th>Date</th>
				                  	<th>Time</th>
				                  	<th>EmployeeID</th>
				                  	<th>Submission Status</th>
				                </tr>
				            </thead>
				            <tbody>
				            	<h1> Unverified </h1>
				                {% for i in context %}
				                {% if i.unit_incharge_approval == None and i.status != "PENDING"  %}
				                <tr data-href="/schoice/{{i.token}}/{{name}} ">
				                	<td>{{i.date}}</td>
				                	<td>{{i.time}}</td>
				                	<td>{{i.emp_id}}</td>
						            <td>{{i.status}}</td>
				                </tr>
				                {% endif %}
				                {% endfor %}
				             </tbody>
				        </table>
				    </div>

				    <div id="approved" class="tab-pane fade fac">
						<table class="table table-bordered table-condensed table-striped table-hover todaytasks">
						   <h1> Approved</h1>
						   <thead>
				                <tr>
				                	<th>Date</th>
				                  	<th>Time</th>
				                  	<th>EmployeeID</th>
				                  	<th>Submission Status</th>
				                </tr>
				            </thead>
							{% for i in context %}
							{% if i.unit_incharge_approval == "YES" %}
							<tr data-href="/schoice/{{i.token}}/{{name}} ">
			                	<td>{{i.date}}</td>
			                	<td>{{i.time}}</td>
			                	<td >{{i.emp_id}}</td>
					            <td>{{i.status}}</td>
				            </tr>
							{% endif %}
							{% endfor %}   
						</table>
					</div>
					<div id="declined" class="tab-pane fade fac">
						<table class="table table-bordered table-condensed table-striped table-hover todaytasks">
						   <h1> Declined </h1>
						   <thead>
				                <tr>
				                	<th>Date</th>
				                  	<th>Time</th>
				                  	<th>EmployeeID</th>
				                  	<th>Submission Status</th>
				                </tr>
				            </thead>
							{% for i in context %}
							{% if i.unit_incharge_approval == "NO" %}
							<tr data-href="/schoice/{{i.token}}/{{name}} ">
			                	<td>{{i.date}}</td>
			                	<td>{{i.time}}</td>
			                	<td >{{i.emp_id}}</td>
					            <td>{{i.status}}</td>
				            </tr>
							{% endif %}
							{% endfor %}   
						</table>
					</div>	
				</div>
			</div>



			    
		</div>		
	</div>
	<script type="text/javascript">

		$(function(){
	    $('.table tr[data-href]').each(function(){
	        $(this).css('cursor','pointer').hover(
	            function(){ 
	                $(this).addClass('active'); 
	            },  
	            function(){ 
	                $(this).removeClass('active'); 
	            }).click( function(){ 
	                document.location = $(this).attr('data-href'); 
	            }
	        );
	    });
	});
	</script>             
</body>
</html>

supervisor/templates/supervisor/monthly.html
<!-- <html>
{% for i in cdvormonthly %}
    {% for name, value in i.items %}
        
           <td> {{ name }} => {{ value }}</td>

        
    {% endfor %}
{% endfor %}
<br><br>
{% for i in datismonthly %}
    {% for name, value in i.items %}
        
            {{ name }} => {{ value }}
        
    {% endfor %}
{% endfor %}
</html> -->
<html>
    <a href="{% url 'supervisor:cdvormonthly' %}">cdvormonthly</a><br>
   
    <a href="{% url 'supervisor:dmemonthly' %}">dmemonthly</a><br>
    <a href="{% url 'supervisor:dscnmonthly' %}">dscnrmonthly</a><br>
    <a href="{% url 'supervisor:ndbmonthly' %}">ndbmonthly</a><br>
    <a href="{% url 'supervisor:scctvmonthly' %}">scctvmonthly</a><br>
    <a href="{% url 'supervisor:vhfmonthly' %}">vhfmonthly</a><br>

</html>

supervisor/templates/supervisor/weekly.html
<html>
    <a href="{% url 'supervisor:cdvorweekly' %}">cdvorweekly</a><br>
    <a href="{% url 'supervisor:datisweekly' %}">datisweekly</a><br>
    <a href="{% url 'supervisor:dmeweekly' %}">dmeweekly</a><br>
    <a href="{% url 'supervisor:dscnweekly' %}">dscnrweekly</a><br>
    <a href="{% url 'supervisor:ndbweekly' %}">ndbweekly</a><br>
    <a href="{% url 'supervisor:scctvweekly' %}">scctvweekly</a><br>
    <a href="{% url 'supervisor:vhfweekly' %}">vhfweekly</a><br>

</html>


    